package formulario.Ciudadanos;

import accesoUI.operaracionesDiagnostico;
import modeloClases.Ciudadano;
import modeloClases.Persona;

public class CiudadanoNuevoForm extends javax.swing.JFrame {

    Ciudadano ciudadano;
    Persona persona;

    public CiudadanoNuevoForm() {
        initComponents();
    }

    public Ciudadano getCiudadano() {
        return ciudadano;
    }

    public void setCiudadano(Ciudadano ciudadano) {
        this.ciudadano = ciudadano;
    }

    public Persona getPersona() {
        return persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VolverBTN = new javax.swing.JButton();
        AceptBTN = new javax.swing.JButton();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        no3 = new javax.swing.JRadioButton();
        no4 = new javax.swing.JRadioButton();
        si4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        no8 = new javax.swing.JRadioButton();
        temperatura = new javax.swing.JTextField();
        si8 = new javax.swing.JRadioButton();
        si7 = new javax.swing.JRadioButton();
        no7 = new javax.swing.JRadioButton();
        no6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        si6 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        si5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no5 = new javax.swing.JRadioButton();
        si9 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        no9 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        si1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        si2 = new javax.swing.JRadioButton();
        si3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VolverBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VolverBTN.setText("Volver");
        VolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBTNActionPerformed(evt);
            }
        });

        AceptBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AceptBTN.setText("Aceptar");
        AceptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBTNActionPerformed(evt);
            }
        });

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox10.setText("Tengo alguna condición que baja las defensas");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Trabajas o convivís con una persona que actualmente sea caso positivo COVID-19");

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Pasaste en los últimos 14 días al menos 15 minutos cerca de una persona que actualmente sea caso confirmado COVID-19");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Estoy embarazada");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("Tengo/tuve cáncer");

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setText("Tengo diabetes");

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox9.setText("Tengo alguna enfermedad hepática");

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8.setText("Tengo enfermedad renal crónica");

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setText("Tengo alguna enfermedad respiratoria");

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox11.setText("Tengo alguna enfermedad cardiológica");

        no3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no3.setText("no");

        no4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no4.setText("no");

        si4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si4.setText("si");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("¿Cuál es su temperatura corporal actual? ");

        no8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no8.setText("no");

        si8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si8.setText("si");

        si7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si7.setText("si");

        no7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no7.setText("no");

        no6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no6.setText("no");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¿Percibiste una marcada perdida del olfato de manera repentina? ");

        si6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si6.setText("si");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("¿Percibiste una marcada perdida del gusto (sabor de los alimentos) de manera repentina?");

        si5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si5.setText("si");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("¿Tenés dolor de garganta? ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("¿Tenés tos? ");

        no5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no5.setText("no");

        si9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si9.setText("si");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("¿Tenés dificultad respiratoria o falta de aire?");

        no9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no9.setText("no");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("¿Tenés dolor de cabeza?");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("¿Tenés vómitos?");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("¿Tenés diarrea?");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("¿Tenés dolor muscular?");

        si1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si1.setText("si");

        no1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no1.setText("no");

        no2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no2.setText("no");

        si2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si2.setText("si");

        si3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        si3.setText("si");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(si2)
                                        .addGap(18, 18, 18)
                                        .addComponent(no2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(si1)
                                        .addGap(18, 18, 18)
                                        .addComponent(no1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(si3)
                                        .addGap(18, 18, 18)
                                        .addComponent(no3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(si5)
                                            .addComponent(si4)
                                            .addComponent(si6)
                                            .addComponent(si7)
                                            .addComponent(si8)
                                            .addComponent(si9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(no4)
                                            .addComponent(no5)
                                            .addComponent(no6)
                                            .addComponent(no7)
                                            .addComponent(no8)
                                            .addComponent(no9)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(AceptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(si1)
                    .addComponent(no1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(si2))
                    .addComponent(no2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(si3)
                    .addComponent(no3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(si4)
                    .addComponent(no4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(si5)
                    .addComponent(no5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(si6)
                    .addComponent(no6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(si7)
                    .addComponent(no7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(si8)
                    .addComponent(no8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(si9)
                    .addComponent(no9))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AceptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBTNActionPerformed
        CiudadanoComuniquese mensajeComuniquese = new CiudadanoComuniquese();
        operaracionesDiagnostico nuevoDiagnostico = new operaracionesDiagnostico();
        int cantSintomas = cantidadSintomas();
        int cantPatologia = cantidadPatologias();
        /*
        En caso de presentar temperatura corporal > 38 grados, presentar al menos 3 síntomas y al menos
        una condición de salud de las listadas previamente, se debe informar al ciudadano que se
        comunique al 0800-777-0801 y su estado es DETECTABLE.
        
         */
        if (Integer.parseInt(temperatura.getText()) > 38 && cantSintomas >= 3 && cantPatologia >= 1) {
            nuevoDiagnostico.AgregarDiagnostico(ciudadano, Integer.parseInt(temperatura.getText()), true, cantSintomas);
            //genero una gestion de diagnostico
            nuevoDiagnostico.generarGestionDiagnostico(nuevoDiagnostico.obtenerSuUltimoDiagnostico(ciudadano), persona);
            
            this.dispose();
            mensajeComuniquese.setVisible(true);
        } else {
            /*Caso contrario, se deberá confirmar la autorización para circular por 48 hs, mostrando la fecha
             de vencimiento del permiso y su estado como NO DETECTABLE*/
            nuevoDiagnostico.AgregarDiagnostico(ciudadano, Integer.parseInt(temperatura.getText()), false, cantSintomas);
            //genero una gestion de diagnostico
            this.dispose();
        }


    }//GEN-LAST:event_AceptBTNActionPerformed

    private void VolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CiudadanoNuevoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CiudadanoNuevoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CiudadanoNuevoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CiudadanoNuevoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CiudadanoNuevoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptBTN;
    private javax.swing.JButton VolverBTN;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JRadioButton no3;
    private javax.swing.JRadioButton no4;
    private javax.swing.JRadioButton no5;
    private javax.swing.JRadioButton no6;
    private javax.swing.JRadioButton no7;
    private javax.swing.JRadioButton no8;
    private javax.swing.JRadioButton no9;
    private javax.swing.JRadioButton si1;
    private javax.swing.JRadioButton si2;
    private javax.swing.JRadioButton si3;
    private javax.swing.JRadioButton si4;
    private javax.swing.JRadioButton si5;
    private javax.swing.JRadioButton si6;
    private javax.swing.JRadioButton si7;
    private javax.swing.JRadioButton si8;
    private javax.swing.JRadioButton si9;
    private javax.swing.JTextField temperatura;
    // End of variables declaration//GEN-END:variables

    public int cantidadSintomas() {
        int cantidad = 0;
        javax.swing.JRadioButton[] sintomas = {
            si1,
            si2,
            si3,
            si4,
            si5,
            si6,
            si7,
            si8,
            si9,};
        for (javax.swing.JRadioButton jRadioButton : sintomas) {
            if (jRadioButton.isSelected()) {
                cantidad++;
            }
        }
        return cantidad;
    }

    public int cantidadPatologias() {
        int cantidad = 0;
        javax.swing.JCheckBox[] sintomas = {
            jCheckBox1,
            jCheckBox2,
            jCheckBox3,
            jCheckBox5,
            jCheckBox6,
            jCheckBox7,
            jCheckBox8,
            jCheckBox9,
            jCheckBox10};
        for (javax.swing.JCheckBox jCheckBox : sintomas) {
            if (jCheckBox.isSelected()) {
                cantidad++;
            }
        }
        return cantidad;
    }

}
